export const userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_CURRENT_USER_DATA: 'SET_CURRENT_USER_DATA',
    UNSET_CURRENT_USER: 'UNSET_CURRENT_USER',
    SET_CURRENT_ROLES: 'SET_CURRENT_ROLES',
    SET_CURRENT_PERMISSIONS: 'SET_CURRENT_PERMISSIONS',
}